### PR TITLE
Refactor styles according to BBBTO

### PR DESCRIPTION
**Pull request by asaenka**
- [x] Fix classes to obey BEM

### CODE REVIEW

**Comment by aj0x0** [comment]
you should merge at some point . 🥇

**Comment by asaenka** [comment]
@Jacob2014 I have  refactored my styles.css and index.html. So now it is ready to merge :)

**Comment by asaenka** [comment]
@Jacob2014 Do you have any ideas for improvement?

**Comment by asaenka** [comment]
Have finished the project.

**Pull request merged**
